name: gazhome
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.3.3
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^18.0.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  flutter_typeahead: ^5.2.0
  fluttertoast: ^8.2.12
  freezed_annotation: ^2.4.4
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get_it: ^8.0.3
  google_maps_flutter: ^2.10.1
  internet_connection_checker_plus: ^2.7.0
  loading_indicator: ^3.1.1
  open_filex: ^4.7.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^11.4.0
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.4.0
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  syncfusion_flutter_pdfviewer: ^28.2.11
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  confetti: ^0.7.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: null
  very_good_analysis: ^7.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/svgs/
    - .env

  fonts:
    - family: NotoKufiArabic
      fonts:
        - asset: assets/fonts/NotoKufiArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoKufiArabic-Bold.ttf
          weight: 700
    - family: Arial
      fonts:
        - asset: assets/fonts/Arial-Regular.ttf
          weight: 400
        - asset: assets/fonts/Arial-Bold.ttf
          weight: 700
